[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymultifracs"
dynamic = ["version"]
description = "Implements wavelet based multifractal analysis of 1d signals."
readme = "README.rst"
authors = [
    { name = "Merlin Dumeur" },
    { name = "Omar Darwiche Domingues" },
    { name = "Roberto Fabio Leonarduzzi" }
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "pywavelets",
    "seaborn",
    "xarray"
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent",
]

[project.urls]
Documentation = "https://www.neurospin.fr/pymultifracs/"
Source = "https://github.com/neurospin/pymultifracs"
Tracker = "https://github.com/neurospin/pymultifracs/issues/"

[project.optional-dependencies]
bootstrap = ["recombinator"]
robust = ["statsmodels", "ruptures", "numba", "tqdm"]
jax = ["jax", "gdm-xarray-jax@git+https://github.com/google-deepmind/xarray_jax.git@v0.1.0"]
full = ["pymultifracs[bootstrap,robust,jax]"]
test = ["pytest", "pytest-xdist", "pytest-cov", "statsmodels", "recombinator", "joblib", "jax"]
doc = ["sphinx", "numpydoc", "pydata-sphinx-theme", "sphinx-gallery", "joblib", "pooch", "myst-parser", "sphinx-tippy"]
dev = ["pymultifracs[bootstrap,robust,test,doc,jax]"]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
include = ["pymultifracs*"]

[tool.setuptools.dynamic]
version = { attr = "pymultifracs._version.__version__" }